### ISSUE TITLE
アルファベットについて

### ISSUE THREAD

**Issue by kubo-aoi** [Hono589/ProjExD#6]
https://github.com/Hono589/ProjExD/blob/93402a31fcbc5b6880cb3ff14f564e4b7e293b9e/ex01/alphabet.py#L22

ちえちゃんと同じく、アルファベットのアスキーコードと文字数が分かってる場合にしか使えないなーと思ったから、それも判定してだせるとよりいいかも...

**Comment by Hono589** [comment]
参考にします！
ありがと！
